version: "3.9"
services:
  mongodb:
    container_name: mongodb
    image: mongo:6.0.1
    restart: always
    volumes:
      - mongodb:/home/db/mongo
  backend:
    container_name: backend
    depends_on:
      - mongodb
    build:
      dockerfile: Dockerfile
    env_file:
      - .env

volumes:
  mongodb: