FROM golang:1.19.0-alpine

RUN set -ex; \
    apk add build-base; \
    apk update; \
    apk add --no-cache git

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify && go clean -testcache

COPY . .

CMD ["go", "test", "-v", "./implementation/repository/...", "./implementation/service/..."]